auto_battle: 全配队通用
region_type_priority:
- 休憩调息
- 挑战-限时
- 战斗-硬币
- 挑战-无伤
- 战斗-鸣徽
- 战斗-武备
- 偶遇事件
- 代价之间
- 邦布商店
- 挚交会谈
- 战斗-道中危机
- 战斗-终结之役
artifact_priority:
- 卡牌 金钱攻势
- 卡牌 优厚分红
- 终结 律动节能器
- 终结
- 绝境
- 通用
buy_only_priority: 1
period_buff_no: 第一个
artifact_priority_2:
- ！！！！  配  置  说  明  ！！！！
- ！！！读完请删除此框内容！！！
- --
- --
- 成就「空洞金融大亨」：在「战线肃清」中获得「金钱攻势」，并携带超过8000枚齿轮硬币通关。
- 挑战副本一定要选择「战线肃清」！「特遣调查」完不成这个成就！
- 建议携带大范围攻击dps最高的角色(如雅耀妮)，以便能尽快打完「挑战-限时」，一关就能拿到1800+的齿轮硬币
- 难度5、6才有「秘宝猎人战略」，建议难度5
- 作战潜能记得点满齿轮硬币相关增益
- 有时候脚本可能刷不到「挑战-限时」或者「挑战-限时」打的慢，可以偶尔暂停看一下是否刷到了「金钱攻势」以便及时换为手刷
artifact_priority_new: true
chase_new_mode: false
investigation_strategy: 秘宝猎人战略
store_gold: false
